[project]
name = "advance-agent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fpdf>=1.7.2",
    "google-generativeai>=0.8.4",
    "openai>=1.68.2",
    "openai-agents>=0.0.6",
    "pdfplumber>=0.11.5",
    "python-dotenv>=1.0.1",
    "speechrecognition>=3.14.2",
    "tiktoken>=0.9.0",
]
